import "osl/ws"
import "osl/requests"
import "osl/fs"

string API_BASE = "https://api.rotur.dev"

array recent_message_listeners = []
object recent_listened_messages = {}
object connections = {}
array servers = ["wss://chats.mistium.com", "wss://dms.mistium.com"]
object commands = {}
object channel_messages = {}
object user_personalities = {}

object config = openObjectFile("./config.json")
string ADMIN_TOKEN = config.admin_token ?? ""

object ADMIN_HEADERS = {
    "Authorization": ADMIN_TOKEN,
    "Content-Type": "application/json",
}

import "./ai/ai.osl"
import "./ai/vercel.osl"
import "./ai/personalities.osl"

import "./utils.osl"
import "./validator.osl"
import "./handler.osl"
import "./rotur.osl"
import "./message_cache.osl"
import "./helpers.osl"

import "./commands/hello.osl"
import "./commands/roturacc.osl"

import "./slashes/balance.osl"
import "./slashes/transfer.osl"

import "./slashes/keys get.osl"
import "./slashes/keys set.osl"
import "./slashes/personality.osl"

import "./handlers/message_new.osl"

mainloop:

    registerCommand("!hello", hello)
    registerCommand("!roturacc", roturacc)

    registerCommand("/balance", balance)
    registerCommand("/transfer", transfer)

registerCommand("/keys get", keys_get)
registerCommand("/keys set", keys_set)
registerCommand("/personality", personality)

    for i servers.len (
        auto connection = ws.Connect(servers[i].toStr())
        connection.OnMessage(messageHandler)
        connection.OnClose(closeHandler)
        connection.data.serverUrl = servers[i]
        connections[servers[i]] = connection
    )

    while true (
        wait 100
    )