import "osl/ws"
import "osl/requests"
import "osl/fs"

string API_BASE = "https://api.rotur.dev"

object connections = {}
array servers = ["wss://chats.mistium.com", "wss://dms.mistium.com"]
object commands = {}

object config = openObjectFile("./config.json")
string ADMIN_TOKEN = config.admin_token ?? ""

import "./utils.osl"
import "./validator.osl"
import "./handler.osl"
import "./rotur.osl"

import "./commands/hello.osl"
import "./commands/roturacc.osl"

import "./slashes/balance.osl"

import "./handlers/message_new.osl"

mainloop:

    registerCommand("!hello", hello)
    registerCommand("!roturacc", roturacc)

    registerCommand("/balance", balance)

    for i servers.len (
        auto connection = ws.Connect(servers[i].toStr())
        connection.OnMessage(messageHandler)
        connection.OnClose(closeHandler)
        connection.data.serverUrl = servers[i]
        connections[servers[i]] = connection
    )

    while true (
        wait 100
    )