def changepass(*Connection c, object msg) (
  string new_password = ""

  any msg_args = msg.args
  if typeof(msg_args) == "object" (
    object args = msg_args.assert(object)
    if args.contains("new_password") (
      new_password = args.new_password.toStr()
    )
  )

  if new_password == "" (
    sendResponse(c, msg, "Usage: /changepass <new_password>")
    return
  )

  string token = getToken(msg.user)
  if token == "" (
    sendResponse(c, msg, "Could not retrieve your auth token.")
    return
  )

  object resp = users_patch(token, "password", new_password)

  if resp.error != null (
    sendResponse(c, msg, resp.error.toStr())
    return
  )

  sendResponse(c, msg, "Your rotur password has been changed.")
)
