def message_new(*Connection c, object json, string token) (
    object msg = json.message
    string content = msg.content

    if content.contains("@roturBOT") (
        object replyMsg = sendReply(c, rawToMsg(json), "hi!")
        log replyMsg
        for i 10 (
            log i
            editMessage(c, replyMsg, "hi! " ++ i.toStr())
            wait 1
        )
        return
    )

    array prefixes = commands.getKeys()
    for i prefixes.len (
        if !content.startsWith(prefixes[i].toStr()) (
            continue
        )

        string new_content = content.trim(prefixes[i].len + 1, -1).strip()
        object msg = rawToMsg(json)
        msg.content = new_content
        commands[prefixes[i]](c, msg)
    )
)