def message_new(*Connection c, object json, string token) (
    object msg = json.message
    string channel = json.channel
    string user = msg.user
    string content = msg.content

    array prefixes = commands.getKeys()
    for i prefixes.len (
        if !content.startsWith(prefixes[i].toStr()) (
            continue
        )

        string new_content = content.trim(prefixes[i].len + 1, -1)
        commands[prefixes[i]](c, {
            user,
            content: new_content,
            channel
        })
    )
)