
def registerStatsCommands() (
  registerSlashCommand("totalusers", totalusers, {
    name: "totalusers",
    description: "Display the total number of rotur users",
    options: [],
    ephemeral: false
  })

  registerSlashCommand("accorigins", accorigins, {
    name: "accorigins",
    description: "Get stats on how many accounts are linked to each rotur OS",
    options: [],
    ephemeral: false
  })

  registerSlashCommand("messages", messages, {
    name: "messages",
    description: "See how many messages you have sent in the past hour, day, week, and month",
    options: [],
    ephemeral: false
  })

  registerSlashCommand("top", top, {
    name: "top",
    description: "See the top 10 most active users in the past week",
    options: [],
    ephemeral: false
  })
)
