def requests_list(*Connection c, object msg) (
  object user = getUserData(msg.user)

  if user.error != null (
    sendResponse(c, msg, user.error.toStr())
    return
  )

  any reqs = user["sys.requests"]

  if reqs == null (
    sendResponse(c, msg, "You have no pending friend requests.")
    return
  )

  if typeof(reqs) != "array" (
    sendResponse(c, msg, "You have no pending friend requests.")
    return
  )

  array arr = reqs.assert(array)
  if arr.len == 0 (
    sendResponse(c, msg, "You have no pending friend requests.")
    return
  )

  sendResponse(c, msg, "Pending friend requests:\n" ++ arr.join("\n"))
)
